apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ns-netflix
    env: dev
  name: ns-netflix
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
  namespace: ns-netflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: stephanezang/weekend_challenge1:netflix
        ports:
        - containerPort: 80
